name: MegaSDK Docker Builds

on:
  push:
    tags:
      - v*.*.*

env:
  IMAGE: ghcr.io/yzop/megasdk

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get Push Type
        id: get_version
        run: echo ::set-output name=VERSION::$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
      - name: Login to ghcr.io Registry
        run: docker login https://ghcr.io -u token -p ${{ secrets.GH_TOKEN }}
        
      - name: Build and Push Docker image
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo VERSION=$VERSION
          echo "Building"
          docker build -t ${{ env.IMAGE }}:$VERSION --build-arg MEGA_SDK_VERSION=$VERSION .
          echo "Pushing"
          docker push ${{ env.IMAGE }}:$VERSION
      
      - name: Build Assets for Release
        run : |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo VERSION=$VERSION
          docker run --name=msdk --rm -dit ${{ env.IMAGE }}:$VERSION bash
          docker cp msdk:/sdk/bindings/python/dist/ ./
          docker cp msdk:/sdk/ ./
          rm -rf sdk/.git && tar -czf megasdk-v$VERSION.tar.gz sdk && rm -rf sdk
          
      - name : Upload Built Files for Latest Release
        uses: softprops/action-gh-release@v1
        with:
          name: MegaSDK Build ${{ steps.get_version.outputs.VERSION }}
          files: |
            dist/megasdk-*.whl
            megasdk-v*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}